// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdfbacmobecizcvvtofq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZmJhY21vYmVjaXpjdnZ0b2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMDQzNzIsImV4cCI6MjA1NTg4MDM3Mn0.31bIUiDIxHz3gjGQJCKZSoZ3I2mEuUduXfmmf250BXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);